name: cd

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 저장소로 부터 CI 서버로 코드를 내려받도록 워크플로우를 구성할 수 있습니다.
      - run: ls -al
      - name: checkout
        uses: actions/checkout@v3
      - run: ls -al

      # SSH를 통해 원격 서버에 접속하여 명령어를 실행할 수 있습니다.
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}

          # 40초 안에 연결 안되면 문제가 사실상 문제가 있는 것으로 간주.
          timeout: 40s

          script: |
            cd ~/Emotions
            ./scripts/deploy.sh
